### ISSUE TITLE
Transition/Zoom failure on html

### ISSUE THREAD

**Issue by pide2000** [synyx/tales#263]
System: Chromium Version 110.0.5481.77 (Official Build) on Fedora 37  

Effect: Position and size of the "slide window" is not as defined in tales. 

Recover: Reload page

Reproduce: On transition process from one slide to another press "back/forward" (arrow left/arrow right) before the transition has finished in final position. After that all slide positions are wrong.

**Comment by fheft** [comment]
Hey Peter,

I was not able to reproduce the issue after following these steps:

1. Export a tale as HTML
2. Open the exported HTML in Chromium (v111.0 in my case)
3. Press arrow left/right keys in fast succession (while the transition is still active)

The new transition always cancelled the ongoing transition and ended on the expected slide. 

Besides me misunderstanding the issue it could be a problem specific to your tale. Could you send me the exported HTML by mail, so I can investigate this further?

**Comment by BuJo** [comment]
Cannot reproduce either...  Just reopen in case this happens to you again Peter o/
